[package]
name = "reverie-narf-adapter"
description = "Narf kernel adapter for the generic Reverie Narf backend core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
narf-lib = { path = "../lib" }
narf-kernel-test = { path = "../verification/kernel-test" }
narf-userspace = { path = "../userspace" }
reverie-narf-core = { git = "https://github.com/rrnewton/reverie", rev = "08a70a2e1562de1602d20e8bf1f6b2238aec7ee5" }

[lints]
workspace = true
